In [1]:
import numpy as np

In [2]:
# scalar quantity 
a=np.array(10)

In [3]:
print(a)

10


In [4]:
print("Add",a + 5)

Add 15


In [6]:
# Vector (1-D array)

vec=np.array([1,2,3,4,5,6])
print(vec)

[1 2 3 4 5 6]


In [7]:
vec * 3

array([ 3,  6,  9, 12, 15, 18])

In [8]:
print(vec + 15)

[16 17 18 19 20 21]


In [9]:
print(vec + vec)

[ 2  4  6  8 10 12]


In [10]:
print(vec - vec)

[0 0 0 0 0 0]


In [11]:
#Matrix (2-D Array) Rows & Columns

mat=np.array([[1,2,3],[4,5,6]])

print(mat)

[[1 2 3]
 [4 5 6]]


In [21]:
mat.shape

(2, 3)

In [12]:
mat + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
mat * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
print(mat + 3)

[[4 5 6]
 [7 8 9]]


In [15]:
Mat1=np.array([[1,2],[3,4]])

Mat2=np.array([[5,6],[7,8]])

In [17]:
Mat1

array([[1, 2],
       [3, 4]])

In [18]:
Mat2

array([[5, 6],
       [7, 8]])

In [16]:
Mat1 + Mat2

array([[ 6,  8],
       [10, 12]])

In [19]:
Mat1 * Mat2

array([[ 5, 12],
       [21, 32]])

(2, 2)

In [22]:
Mat1

array([[1, 2],
       [3, 4]])

In [23]:
#Transpose a matrix
Mat1.T

array([[1, 3],
       [2, 4]])

In [24]:
#determinant
A=np.array([[1,2],[3,4]])


In [25]:
A

array([[1, 2],
       [3, 4]])

In [29]:
det=np.linalg.det(A)
print(det)

det=ad-bc

-2.0000000000000004


In [ ]:
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
det=np.linalg.det(B)
print(det)

0.0


In [ ]:
det=a(ei-fh)-b(di-fg)+c(dh-eg)

In [32]:
#identity matrix

Iden=np.eye(3)
print(Iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#Diagonal Matrix

diag=np.diag([1,5,9])
print(diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [53]:
# linear Equation 
A=np.array([[4,5,3],
            [4,1,6],
            [9,8,9]
           ])

B=np.array([6,8,9])

In [54]:
#Solve linear equation

X=np.linalg.solve(A, B)
print(X)

[-53.          24.          32.66666667]


In [55]:
A

array([[4, 5, 3],
       [4, 1, 6],
       [9, 8, 9]])

In [56]:
C

array([5, 6])